version: '3.8'

# Supported values: v1, v2
# When you change MODEL_VERSION and push to main branch,
# it will automatically deploy to EC2
services:
  ml-api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_VERSION=${MODEL_VERSION:-v2}  # CHANGE THIS: v1 or v2
      - PYTHONPATH=/app
    labels:
      - "ml.version=${MODEL_VERSION:-v2}"     # For tracking
      - "ml.auto-deploy=true"                 # Enable auto-deploy