version: '3.8'

services:
  ml-api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_VERSION=${MODEL_VERSION:-v1}
      - PYTHONPATH=/app